name: Parallel

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: {8,11,17}

    steps:
      - name: checkout code
        uses: actions/setup-java@v4

      - name: set up SDK ${{matrix.java-version}}
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: ${{matrix.java-version}}

      - name: Build with maven
        run: mvn clean install
      